- name: create sonarqube user
  ansible.builtin.user:
    name: sonarqube

- name: create sonarqube directory
  ansible.builtin.file:
    path: /sonarqube
    state: directory
    owner: sonarqube
    group: sonarqube

- name: download sonarqube
  ansible.builtin.unarchive:
    src: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-25.2.0.102705.zip
    dest: /sonarqube
    owner: sonarqube
    group: sonarqube
    remote_src: yes

- name: install java
  ansible.builtin.dnf:
    name: java-17-openjdk
    state: installed

- name: sonarqube servicefile copy
  ansible.builtin.template:
    src: sonarqube.service
    dest: /etc/systemd/system/sonarqube.service

- name: start sonarqube service
  ansible.builtin.systemd_service:
      name: sonarqube
      state: started
      enabled: yes
      daemon-reload: yes



