- name: create sonarqube user
  ansible.builtin.user:
    name: sonarqube

- name: create sonarqube directory
  ansible.builtin.file:
    name: sonarqube
    state: directory
    owner: sonarqube
    group: sonarqube

- name: download sonarqube
  ansible.builtin.unarchive:
    url: https://binaries.sonarsource.com/CommercialDistribution/sonarqube-developer/sonarqube-developer-2025.1.0.102418.zip
    dest: /sonarqube
    owner: sonarqube
    group: sonarqube
    remote_src: yes

- name: install java
  ansible.builtin.dnf:
    name: java-11-openjdk
    state: present


#- name: install sonarqube
#  ansible.builtin.shell: /sonarqube/bin/linux-x86-64/sonar.sh start
#  become_user: sonarqube



