- name: Add github runner user
  ansible.builtin.user:
    name: github-runner
    home: /github-runner

- name: Download runner software
  ansible.builtin.unarchive:
    src: https://github.com/actions/runner/releases/download/v2.322.0/actions-runner-linux-x64-2.322.0.tar.gz
    dest: /github-runner
    owner: github-runner
    group: github-runner
    remote_src: yes

- name: Install libicu
  ansible.builtin.dnf:
    name: libicu
    state: installed

#- name: Configure runner
#  ansible.builtin.shell: ./config.sh --url https://github.com/azawsdevops --token BCKQBLB724QBV6WNSPIL5C3HVUHA6 --unattended --name github-runner-az --labels default --replace --work _work
#  args:
#    chdir: /github-runner
#  become_user: github-runner
#  ignore_errors: yes
#    
#- name: Copy Service
#  ansible.builtin.template:
#    src: github-runner.service
#    dest: /etc/systemd/system/github-runner.service
#
#- name: Start Service
#  ansible.builtin.systemd_service:
#    name: github-runner
#    state: restarted
#    enabled: yes
#    daemon-reload: yes